# LambdaTest Configuration

# Project and folder configuration
project_id: "01JF008HHYQF0YZDPSGRAVDMQ4"
folder_id: "01KSFJ9AD5HNEA33K340VMNV9S"

# Test Run configuration
assignee: 1699830
environment_id: 284298

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
